### ISSUE TITLE
"be_sng_13" may be wrong

### ISSUE THREAD

**Issue by tianyuanhao** [kaCVanime/AnkiEnJa#9]
From the explanation, this word should be the verb `cost`. Perhaps `be` and `cost` have been mixed together.

**Comment by kaCVanime** [comment]
![{FE096115-C481-4AA3-8404-957B0D9104B9}](https://github.com/user-attachments/assets/ba9e1dd5-6e2d-4560-90c6-c6eefbd0356e)

Actually "be" has a sense of "cost".  

The note has wrong extra examples, indeed. This is because these extra examples are generated by AI, any it usually starts hallucinating when came across similar sense. Currently I'm working on removing those wrong examples in batch.
